title: Tao Zhang's Homepage
page-top-title: Tao Zhang
top-section-bg-text: Control Science & Technology
home-subtitle: Tao Zhang&ensp;|&ensp;张涛
copyright-text: '&copy; Tao Zhang 2025-2099. All Rights Reserved.'
